### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fael0306** [ericbrasiln/pyHDB#17]
**Descreva o bug**
O programa roda, porém, o script sempre encontra 0 ocorrências, mesmo elas existindo na Hemeroteca.

**Reproduzir**
Foi seguido exatamente o passo a passo solicitado. Foi feita a tentativa no Windows e no Linux, em diferentes computadores, sem sucesso.

**Comportamento esperado**
Era para aparecer as ocorrências na pasta, conforme a documentação. Ele sequer encontra ocorrências.

**Screenshots**
![image](https://github.com/ericbrasiln/pyHDB/assets/25599308/5d6029bc-d667-4c2e-bb03-d757c7102fa5)

**Desktop (por favor, preencha as seguintes informações):**
  - SO: Linux Mint, Windows 10 e Windows 11
  - Versão do Python: 3.11
- Terminal ou terminal virtual: CMD, PowerShell e Terminal (Linux Mint)

**Comment by ericbrasiln** [comment]
Olá @fael0306 

Mujito obrigado pelo contato e pelo interesse na ferramenta.

Desculpe a demora em responder.

Alguma coisa aconteceu com o site da HDB que está causando esse funcionamento na pyHDB. 
Ainda não consegui descobrir o que é!

No mês de julho vou retomar essa issue e buscar a solução.

Enquanto isso, você pode tentar executar o arquivo `pyHDB_acervos.py`.

Ele faz a busca em um acervo (pasta do jornal) ou lista de acervos.  Para isso você precisa informar o número do acervo. Esse número (que geralmente representa um pasta de uma década de um determinado periódico), pode ser encontrado de algumas maneiras.

## 1) Buscar no código fonte da página dos resultados:

Se você inspecionar a página de resultados, e buscar `#BibMaisButton`, você encontrará as 50 tags que contém informações sobre as ocorrências e seus acervos. O número do acervo está nessa tag, como mostrado na imagem. Assim, você consegue encontrar todos os acervos que tem ocorrências de sua busca.

![bib_mais](https://github.com/ericbrasiln/pyHDB/assets/58128421/2c848bee-ae06-4fce-8a11-4450df2aa610)

## 2) Encontrar o número na url de um acervo:

Se você clicar em um acervo na lista de resultado, abrirá a página da primeira ocorrência. Nessa url você encontra um numero entre `bib=` e `&pesq=`. Esse é o número do acervo.

![bib_hdb](https://github.com/ericbrasiln/pyHDB/assets/58128421/e0397ee1-62da-40eb-b9bb-150cfec3716a)

## Exemplo de execução do `pyHDB_acervos.py`

https://github.com/ericbrasiln/pyHDB/assets/58128421/d52d9dde-40a1-48e3-a60e-b9ea3e52c367

**Comment by fael0306** [comment]
Boa tarde, Eric.

Da forma alternativa funcionou perfeitamente.

Muito obrigado!

Espero que consiga fazer o programa principal voltar a funcionar perfeitamente.

Abraços.
😁
