### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fael0306** [ericbrasiln/pyHDB#21]
**Descreva o bug**
Aparentemente a versão do ChromeDriver utilizado não condiz com a versão do Google Chrome atual. Mesmo atualizando o ChromeDriver, o programa indica este erro.

**Reproduzir**
O comportamento é visto quando executo o código via terminal com:
python3 pyHBD.py

**Comportamento esperado**
O programa deveria continuar executando, me dando as opções que nele existem.

**Screenshots**
![image](https://github.com/ericbrasiln/pyHDB/assets/25599308/e6e0dc43-2b2d-4625-a218-17b87147d79b)

**Desktop (por favor, preencha as seguintes informações):**
  - SO: Linux Mint 21.2
  - Versão do Python: 3.10.12
  - Terminal ou terminal virtual: Terminal do Linux Mint 21.2

**Informações adicionais:**
Testei o pyHDB_acervos.py e ocorre o mesmo erro.
Baixei e testei o ChromeDriver mais atualizado e o erro segue.
Acredito que seja algum problema com a versão utilizada no código mesmo.

**Comment by ericbrasiln** [comment]
Bom dia, @fael0306 
Muito obrigado por abrir a issue. Esse erro também estava acontecendo comigo antes do último release da ferramenta. 

Você pode me falar qual sua versão do selenium? (executa um `pip show selenium` e cola o resultado aqui, por favor).

Esse problema tem sido debatido no [Stackoverflow tb](https://stackoverflow.com/questions/76727774/selenium-webdriver-chrome-115-stopped-working/76731553#76731553).

Abraços

**Comment by fael0306** [comment]
Opa. Boa noite, Eric.

Segue a versão do Selenium: 4.9.1

![image](https://github.com/ericbrasiln/pyHDB/assets/25599308/8670b756-cbde-4e0d-8e54-85915594cceb)

**Comment by ericbrasiln** [comment]
Esse problema será resolvido se vc atualizar o Selenium para as versões posteriores a 4.10.

Com o código abaixo vc faz o updage pra a versão mais recente.

```bash
pip install -U selenium
```

Veja se resolve.

**Comment by fael0306** [comment]
Oi, Eric.

Esqueci de responder.
Já utilizei várias vezes o programa. Está funcionando tanto no Mint novamente quanto no Ubuntu.
Obrigado pelos retornos!

Abraços.
