### ISSUE TITLE
[BUG] Ferramenta não concluindo raspagem

### ISSUE THREAD

**Issue by josemiguel2001** [ericbrasiln/pyHDB#24]
**Descreva o bug**

Primeiramente, gostaria de agradecer ao Eric por essa ferramenta interessantíssima que promete facilitar bastante o meu trabalho no projeto de pesquisa no qual faço parte. Tenho tentado utilizar a ferramenta tanto com a sua opção mais geral (pyHDB.py), quanto com a opção relativa aos acervos e, em ambos os casos, não tenho conseguido obter os CSV's relativos aos resultados das ocorrências. Obtenho somente um relatório txt geral com algumas poucas informações. Abaixo, um exemplo do único arquivo que a ferramenta tem gerado, seguindo, inclusive, a reprodução de um issue já resolvido no fórum.

![informações incompletas - relatório](https://github.com/user-attachments/assets/df7eaad3-7875-437c-a699-af25143a2442)

**Reproduzir**

Tenho usado as seguintes linhas de código:

cd C:\Users\FCJA_GEARQ\Desktop\pyHDB\src
python pyHDB.py e python pyHDB_acervos.py

Utilizando a numeração de acervo "103730_06", referente ao jornal "Gazeta de Notícias", e pesquisando "revolucao de outubro". Nota-se, tenho pesquisado vários termos, alguns bem gerais, outros bem específicos, e sigo sem obter os csv's de resultado e resposta da ferramenta.

![Captura de tela 2024-10-15 111618](https://github.com/user-attachments/assets/81ab16bf-ebba-4ebf-9f4a-d84da3450dea)

**Comportamento esperado**
 Seguindo o acompanhamento de alguns issues aqui, esperaria que a ferramenta demonstrasse, no terminal, alguma informação acerca do andamento do processo de raspagem, além dos já citados resultados em CSV.

**Screenshots**

Abaixo, alguns screenshots demonstrando o que venho obtendo.

![Captura de tela 2024-10-15 112624](https://github.com/user-attachments/assets/f7f6abb2-f60a-48db-8b92-f63c9d630816)

**Desktop (por favor, preencha as seguintes informações):**
  - SO: Windows 11
  - Versão do Python: 3.13
- Terminal ou terminal virtual: PowerShell 7.4.5

**Comment by farnathan** [comment]
Estou com o mesmo problema.

**Comment by ericbrasiln** [comment]
Boa tarde @josemiguel2001 e @farnathan 

Primeiramente, desculpe a demora em responder.

Infelizmente, parece que o site da Hemeroteca Digital Brasileira passou a impedir o acesso automatizado, impossibilitando o funcionamento da ferramenta.

Para acompanhar, veja a issue https://github.com/ericbrasiln/pyHDB/issues/25
