### ISSUE TITLE
Não consigo executar 

### ISSUE THREAD

**Issue by DaianeRossi12** [ericbrasiln/pyHDB#5]
# Oi Eric! Help!
Não estou conseguindo executar a raspagem. Estou principalmente com 2 problemas:
1.  Na **instalação do urllib.requests** aparecem os sguintes erros:
ERROR: Could not find a version that satisfies the requirement urllib.requests (from versions: none)
ERROR: No matching distribution found for urllib.requests

1.  Depois de instalar as outras bibliotecas, baixar o script, clonar o repositório, qunado vou **instalar os requisitos** e colocar o local onde armazenei, aparece o erro:
*O sistema não pode encontrar o arquivo especificado*.
![Sem título](https://user-images.githubusercontent.com/102109534/163290500-577abe32-43bf-4e8e-8faa-ad823cab6df2.png)
---
Não sei se estou errando no meio do caminho, mas tô há horas quebrando a cabeça e não vai.. Se vc tiver alguma dica para me dar, agradeço imenso!!

**Comment by ericbrasiln** [comment]
Oi @DaianeRossi12 

Sobre o ponto 1: O módulo urllib.requests já está inserido no python por padrão, não há necessidade de instalar (preciso remover do requirements.txt!!!)

Sobre o ponto 2: me parece apenas algum problema de encontrar o caminho para a pasta. Acho que tem um erro de sintaxe ali. Você deve colocar o caminho para a pasta `src` sem o `<` e o `> `.

```
cd C:\User\Daiane Rossi\Documents\Humanidades Digitais\pyHDB-main\pyHDB\src
```

Ou ainda, vc pode tentar  clicar direto na pasta `src` com o botão direito e abrir com o powershell (acho que o windows tem essa opção).

Se funcionar me avise. E se der mais erros também (pq foi desenvolvida no linux, e mesmo eu tentando adaptar pra rodar no windows, pode dar probelmas).

Lembrando que é preciso ter o google chrome instalado tb.

**Comment by DaianeRossi12** [comment]
Consegui!!! 
Tudo certo! 
Uma dica essencial é executar o cmd com privilégios de adm. :)))
